### ISSUE TITLE
Permission request

### ISSUE THREAD

**Issue by tsjam23** [Zulko/sheet-music--Gershwin-sweet-and-lowdown#1]
Thank you for your work!
1. Is your work also in public domain? May I ask for permission to publish it at musescore.com?
2. How accurately does this work reflect the piano roll? Neither you nor Artis Wodehouse plays this place as even as it is written in this score (almost all is eighth notes):
![image](https://github.com/Zulko/sheet-music--Gershwin-sweet-and-lowdown/assets/133224452/8f994335-82c0-4dd8-a8e9-35d892c7ef8a)

**Comment by Zulko** [comment]
Yes my transcription is also in the public domain and you can publish it on musescore.com (bonus points if you give some credit :D)

Regarding the eighth notes, this is a shortcut I take, where the performer is expected to add the "swing" and play the two eighth of each beat as a "quarter-and-eighth triplet". This works generally well for pieces that have the same swing throughout, but Sweet and Lowdown may a mix of swingy parts and non-swingy ones so it might be worth adding some details.

**Comment by tsjam23** [comment]
> Yes my transcription is also in the public domain and you can publish it on musescore.com (bonus points if you give some credit :D)
> 
> Regarding the eighth notes, this is a shortcut I take, where the performer is expected to add the "swing" and play the two eighth of each beat as a "quarter-and-eighth triplet". This works generally well for pieces that have the same swing throughout, but Sweet and Lowdown may a mix of swingy parts and non-swingy ones so it might be worth adding some details.

Thank you very much for your help.
Here is musescore version I made https://musescore.com/user/8907766/scores/11039149
I am attaching an archive with musescore and musicxml files in case you want to add them to the repository.
[Sweet and Lowdown_musescore_musicxml.zip](https://github.com/Zulko/sheet-music--Gershwin-sweet-and-lowdown/files/11637653/Sweet.and.Lowdown_musescore_musicxml.zip)
